# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=13)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('unit', models.CharField(max_length=10)),
                ('minQuantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=13)),
                ('barcode', models.CharField(max_length=13)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('unitCost', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('quantity', models.FloatField()),
                ('minQuantity', models.FloatField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.Family')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.Location')),
            ],
        ),
    ]
