# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-12 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_auto_20181211_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
